---
fixtures:
  repositories:
    augeasproviders_core: https://github.com/simp/augeasproviders_core.git
    augeasproviders_sysctl: https://github.com/simp/augeasproviders_sysctl.git
    cron_core:
      repo: https://github.com/simp/pupmod-puppetlabs-cron_core.git
      puppet_version: ">= 6.0.0"
    simplib: https://github.com/simp/pupmod-simp-simplib.git
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
  symlinks:
    swap: "#{source_dir}"
